version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=app
      - DB_PASSWORD=app_pw
      - DB_NAME=meubanco
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_pw
      - MYSQL_DATABASE=meubanco
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app_pw
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot_pw"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
